#!/bin/bash

font='-*-terminus-medium-*-*-*-*-*-*-*-*-*-*-*'
normbgcolor='#181818'
normfgcolor='#e9e9e9'
selbgcolor='#dd6003'
selfgcolor='#e9e9e9'


pkill -x dmenu
xdotool search --class conky windowunmap %@

curname=$(bspc control --get-status | sed -e 's/.*O\([^:]*\):.*/\1/')
nextdesk=$(echo $curname |dmenu -p "desktop name [$curname]:" -fn $font -nb $normbgcolor -nf $normfgcolor -sb $selbgcolor -sf $selfgcolor -x 144 -w 1500 || echo $curname)

if [ "$nextdesk" != "" ]
then
  nextesk=$curname
fi

bspc desktop --rename "$nextdesk"
